services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      CB_SERVER_NAME: ${CB_SERVER_NAME}
      CB_SERVER_URL: ${CB_SERVER_URL}
      CB_ADMIN_NAME: ${CB_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD}
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  cloudbeaver_data:
