"""add preflop responses tables

Revision ID: 13ee4b673b3f
Revises: e8a8fc56d100
Create Date: 2026-07-01 20:39:45.139582

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13ee4b673b3f"
down_revision: str | Sequence[str] | None = "e8a8fc56d100"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preflop_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("table_size", sa.SmallInteger(), nullable=False),
        sa.Column(
            "hero_position",
            sa.Enum(
                "UTG",
                "UTG+1",
                "UTG+2",
                "LJ",
                "HJ",
                "CO",
                "BTN",
                "SB",
                "BB",
                name="poker_position",
            ),
            nullable=False,
        ),
        sa.Column("hero_stack_bb", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("small_blind_bb", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("big_blind_bb", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "ante_bb",
            sa.Numeric(precision=6, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("hero_card_1", sa.String(length=2), nullable=False),
        sa.Column("hero_card_2", sa.String(length=2), nullable=False),
        sa.Column(
            "move",
            sa.Enum("fold", "call", "raise", "allin", name="preflop_move"),
            nullable=False,
        ),
        sa.Column("raise_size_bb", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "verdict",
            sa.Enum("correct", "acceptable", "incorrect", name="preflop_verdict"),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "recommended_move",
            sa.Enum("fold", "call", "raise", "allin", name="preflop_move"),
            nullable=False,
        ),
        sa.Column(
            "recommended_raise_size_bb", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("table_size BETWEEN 2 AND 9"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_preflop_responses_user_id"),
        "preflop_responses",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "preflop_response_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("response_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column(
            "position",
            sa.Enum(
                "UTG",
                "UTG+1",
                "UTG+2",
                "LJ",
                "HJ",
                "CO",
                "BTN",
                "SB",
                "BB",
                name="poker_position",
            ),
            nullable=False,
        ),
        sa.Column(
            "action_type",
            sa.Enum(
                "fold", "limp", "raise", "reraise", "allin", name="preflop_action_type"
            ),
            nullable=False,
        ),
        sa.Column("size_bb", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["response_id"], ["preflop_responses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("response_id", "sequence"),
    )
    op.create_index(
        op.f("ix_preflop_response_actions_response_id"),
        "preflop_response_actions",
        ["response_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_preflop_response_actions_response_id"),
        table_name="preflop_response_actions",
    )
    op.drop_table("preflop_response_actions")
    op.drop_index(op.f("ix_preflop_responses_user_id"), table_name="preflop_responses")
    op.drop_table("preflop_responses")
    # ### end Alembic commands ###
    bind = op.get_bind()
    sa.Enum(name="preflop_action_type").drop(bind, checkfirst=True)
    sa.Enum(name="preflop_verdict").drop(bind, checkfirst=True)
    sa.Enum(name="preflop_move").drop(bind, checkfirst=True)
    sa.Enum(name="poker_position").drop(bind, checkfirst=True)
