"""replace email with first and last name

Revision ID: 53028c5904ec
Revises: 98066ec9e0bb
Create Date: 2026-07-01 21:13:28.062314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53028c5904ec"
down_revision: Union[str, Sequence[str], None] = "98066ec9e0bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=100), nullable=True))
    op.execute(
        "UPDATE users SET first_name = '', last_name = '' WHERE first_name IS NULL"
    )
    op.alter_column("users", "first_name", nullable=False)
    op.alter_column("users", "last_name", nullable=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Original email values are gone; this restores a nullable, non-unique
    # column only so the schema shape matches, not the lost data.
    op.add_column("users", sa.Column("email", sa.VARCHAR(length=255), nullable=True))
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
