"""cascade delete preflop responses on user delete

Revision ID: 98066ec9e0bb
Revises: 13ee4b673b3f
Create Date: 2026-07-01 21:03:58.949628

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98066ec9e0bb"
down_revision: str | Sequence[str] | None = "13ee4b673b3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("preflop_responses_user_id_fkey"), "preflop_responses", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("preflop_responses_user_id_fkey"),
        "preflop_responses",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("preflop_responses_user_id_fkey"), "preflop_responses", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("preflop_responses_user_id_fkey"),
        "preflop_responses",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
