"""add role to users

Revision ID: e8a8fc56d100
Revises: 56685303b953
Create Date: 2026-07-01 20:10:12.742570

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8a8fc56d100"
down_revision: Union[str, Sequence[str], None] = "56685303b953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum("free", "premium", "admin", name="user_role")
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users", sa.Column("role", user_role, server_default="free", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
