FROM ghcr.io/astral-sh/uv:alpine

WORKDIR /app

COPY apps/api/pyproject.toml apps/api/uv.lock ./
RUN uv sync --frozen

CMD ["sh", "-c", "uv run alembic upgrade head && uv run uvicorn app.main:app --reload --host 0.0.0.0 --port ${API_PORT}"]
